# Site settings
title:          Wanderers Web
description:    "Rubber ducking my thoughts and experiences"
baseurl:        "/"
url:            "https://aditya0224.github.io"

# Author
author:
  name:         Aditya Bhamidipati
  url:          http://wanderersweb.com
  email:        adityabh.in@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
